development:
  dialect: postgres
  database: gbfm_development
  user: postgres
  password: postgres
  host: 127.0.0.1
  pool: 5

test:
  dialect: postgres
  database: gbfm_testing
  user: postgres
  password: postgres
  host: 127.0.0.1
  pool: 5

production:
  url: {{envOr "DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/gophersnacks_production?sslmode=disable"}}
