# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true

[[constraint]]
  name = "github.com/dgrijalva/jwt-go"
  version = "3.2.0"

[[constraint]]
  name = "github.com/gobuffalo/buffalo"
  version = "0.11.0"

[[constraint]]
  name = "github.com/gobuffalo/envy"
  version = "1.6.2"

[[constraint]]
  name = "github.com/gobuffalo/packr"
  version = "1.10.7"

[[constraint]]
  name = "github.com/gobuffalo/pop"
  version = "4.5.0"

[[constraint]]
  name = "github.com/gobuffalo/suite"
  version = "2.1.0"

[[constraint]]
  name = "github.com/gobuffalo/uuid"
  version = "2.0.0"

[[constraint]]
  name = "github.com/gobuffalo/validate"
  version = "2.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/murlokswarm/log"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  branch = "master"
  name = "github.com/unrolled/secure"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[override]]
  revision = "36e9d2ebbde5e3f13ab2e25625fd453271d6522e"
  name = "github.com/satori/go.uuid"

[[override]]
  revision = "138548ee992b3b70c9e75e81f9aaa1744d49adfe"
  name = "github.com/qor/admin"

[[override]]
  revision = "f171bc73933e0fbcad81997e9c169f4e7d36f6ba"
  name = "github.com/qor/qor"

[[override]]
  revision = "0555e49f99acf5467a77747fc855d7e005d902c1"
  name = "github.com/qor/mailer"

[[override]]
  revision = "63566e46f01b134ae9882a59a06518e82a903231"
  name = "github.com/qor/render"

[prune]
  go-tests = true
  unused-packages = true
