package actions

import (
	"github.com/gobuffalo/buffalo"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Guide)
// DB Table: Plural (guides)
// Resource: Plural (Guides)
// Path: Plural (/guides)
// View Template Folder: Plural (/templates/guides/)

// GuidesResource is the resource for the Guide model
type GuidesResource struct {
	buffalo.Resource
}

// List gets all Guides. This function is mapped to the path
// GET /guides
func (v GuidesResource) List(c buffalo.Context) error {
	return nil
}

// Show gets the data for one Guide. This function is mapped to
// the path GET /guides/{guide_id}
func (v GuidesResource) Show(c buffalo.Context) error {
	return nil
}
