package actions

import (
	"github.com/gobuffalo/buffalo"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Series)
// DB Table: Plural (series)
// Resource: Plural (Series)
// Path: Plural (/series)
// View Template Folder: Plural (/templates/series/)

// SeriesResource is the resource for the Series model
type SeriesResource struct {
	buffalo.Resource
}

// List gets all Series. This function is mapped to the path
// GET /series
func (v SeriesResource) List(c buffalo.Context) error {
	return nil
}

// Show gets the data for one Series. This function is mapped to
// the path GET /series/{series_id}
func (v SeriesResource) Show(c buffalo.Context) error {

	return nil
}
